spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:admin}
  secret-key: ${MINIO_SECRET_KEY:password}
  bucket: ${MINIO_BUCKET:tevc-cms}

logging:
  level:
    org:
      springframework:
        security: DEBUG

file:
  upload-dir: ${FILE_UPLOAD_DIR:/uploads}
