spring:
  datasource:
    url: jdbc:mysql://prod-db-host:3306/tevc_cms_prod
    username: prod_user
    password: prod_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # Disable automatic schema updates in production
    show-sql: false # Disable SQL query logging in production

  liquibase:
    contexts: production

logging:
  level:
    root: INFO
    org.springframework: WARN
